(function () {
  "use strict";

  const CATALOG_CHECKED_AT = "2026-08-13";

  const courseRating = (value, count) => ({
    value,
    scale: 5,
    count,
    source: "Udemy",
    checkedAt: CATALOG_CHECKED_AT,
  });

  const variableUdemyPrice = () => ({
    label: "Preço variável na Udemy",
    qualifier: "O valor muda conforme conta, região e promoção ativa.",
    variable: true,
    checkedAt: CATALOG_CHECKED_AT,
  });

  const COURSE_CATALOG = {
    "udemy-react-complete-guide": {
      id: "udemy-react-complete-guide",
      title: "React — The Complete Guide (incl. Next.js, Redux)",
      provider: "Udemy",
      instructor: "Academind by Maximilian Schwarzmüller",
      level: "Do básico ao avançado",
      language: "Inglês",
      url: "https://www.udemy.com/course/react-the-complete-guide-incl-redux/",
      rating: courseRating(4.7, 240616),
      price: variableUdemyPrice(),
    },
    "udemy-web-developer-bootcamp": {
      id: "udemy-web-developer-bootcamp",
      title: "The Web Developer Bootcamp 2026",
      provider: "Udemy",
      instructor: "Colt Steele",
      level: "Do básico ao avançado",
      language: "Inglês",
      url: "https://www.udemy.com/course/the-web-developer-bootcamp/",
      rating: courseRating(4.7, 285640),
      price: variableUdemyPrice(),
    },
    "udemy-nodejs-complete-guide": {
      id: "udemy-nodejs-complete-guide",
      title: "NodeJS — The Complete Guide (MVC, REST APIs, GraphQL, Deno)",
      provider: "Udemy",
      instructor: "Academind by Maximilian Schwarzmüller",
      level: "Do básico ao avançado",
      language: "Inglês",
      url: "https://www.udemy.com/course/nodejs-the-complete-guide/",
      rating: courseRating(4.6, 55058),
      price: variableUdemyPrice(),
    },
    "udemy-python-luiz-otavio": {
      id: "udemy-python-luiz-otavio",
      title: "Curso de Python 3 do básico ao avançado — com projetos reais",
      provider: "Udemy",
      instructor: "Luiz Otávio Miranda e Tales Calogi Malaquias",
      level: "Do básico ao avançado",
      language: "Português",
      url: "https://www.udemy.com/course/python-3-do-zero-ao-avancado/",
      rating: courseRating(4.8, 69133),
      price: variableUdemyPrice(),
    },
    "udemy-fullstack-angela-yu": {
      id: "udemy-fullstack-angela-yu",
      title: "The Complete Full-Stack Web Development Bootcamp",
      provider: "Udemy",
      instructor: "Dr. Angela Yu",
      level: "Do básico ao avançado",
      language: "Inglês",
      url: "https://www.udemy.com/course/the-complete-web-development-bootcamp/",
      rating: courseRating(4.7, 470229),
      price: variableUdemyPrice(),
    },
    "udemy-power-bi-maven": {
      id: "udemy-power-bi-maven",
      title: "Microsoft Power BI Desktop for Business Intelligence",
      provider: "Udemy",
      instructor: "Maven Analytics, Chris Dutton e Aaron Parry",
      level: "Do básico ao avançado",
      language: "Inglês",
      url: "https://www.udemy.com/course/microsoft-power-bi-up-running-with-power-bi-desktop/",
      rating: courseRating(4.6, 194125),
      price: variableUdemyPrice(),
    },
    "udemy-python-data-science": {
      id: "udemy-python-data-science",
      title: "Python for Data Science and Machine Learning Bootcamp",
      provider: "Udemy",
      instructor: "Jose Portilla e Pierian Training",
      level: "Intermediário",
      language: "Inglês",
      url: "https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/",
      rating: courseRating(4.6, 159737),
      price: variableUdemyPrice(),
    },
    "udemy-software-testing-masterclass": {
      id: "udemy-software-testing-masterclass",
      title: "Software Testing Masterclass (2026) — From Novice to Expert",
      provider: "Udemy",
      instructor: "Ozan Ilhan",
      level: "Do básico ao avançado",
      language: "Inglês",
      url: "https://www.udemy.com/course/software-testing-masterclass-from-novice-to-expert/",
      rating: courseRating(4.6, 12445),
      price: variableUdemyPrice(),
    },
    "udemy-introduction-software-qa": {
      id: "udemy-introduction-software-qa",
      title: "Introduction to Software Testing or Software QA",
      provider: "Udemy",
      instructor: "Admas Kinfu",
      level: "Iniciante",
      language: "Inglês",
      url: "https://www.udemy.com/course/introduction-to-software-testing-or-software-qa/",
      rating: courseRating(4.5, 8859),
      price: {
        label: "Grátis",
        value: 0,
        currency: "BRL",
        variable: false,
        checkedAt: CATALOG_CHECKED_AT,
      },
    },
    "udemy-decoding-devops": {
      id: "udemy-decoding-devops",
      title: "Decoding DevOps — From Basics to Advanced Projects with AI",
      provider: "Udemy",
      instructor: "Imran Teli",
      level: "Do básico ao avançado",
      language: "Inglês",
      url: "https://www.udemy.com/course/decodingdevops/",
      rating: courseRating(4.6, 47381),
      price: variableUdemyPrice(),
    },
    "udemy-docker-kubernetes-practical": {
      id: "udemy-docker-kubernetes-practical",
      title: "Docker & Kubernetes: The Practical Guide",
      provider: "Udemy",
      instructor: "Academind by Maximilian Schwarzmüller",
      level: "Do básico ao avançado",
      language: "Inglês",
      url: "https://www.udemy.com/course/docker-kubernetes-the-practical-guide/",
      rating: courseRating(4.7, 37452),
      price: variableUdemyPrice(),
    },
  };

  const educationPrice = (label, note) => ({
    label,
    checkedAt: CATALOG_CHECKED_AT,
    note: note || "Valor sujeito a alteração pela instituição.",
  });

  const courseEvaluation = (value, metric, label, sourceUrl) => ({
    value,
    scale: value == null ? null : 5,
    metric: metric || null,
    label,
    source: "MEC/e-MEC",
    sourceUrl: sourceUrl || null,
  });

  const institutionEvaluation = (institution, value, sourceUrl) => ({
    value,
    scale: 5,
    metric: institution === "FIAP" || institution === "FIAP + Alura" ? "Avaliação institucional MEC" : "Conceito Institucional MEC",
    label: institution === "FIAP" || institution === "FIAP + Alura" ? `Nota institucional ${value}/5 no MEC` : `Conceito Institucional ${value}/5`,
    source: "MEC/e-MEC",
    sourceUrl,
  });

  const EDUCATION_CATALOG = {
    "grad-fiap-ads": {
      id: "grad-fiap-ads",
      kind: "Graduação",
      title: "Análise e Desenvolvimento de Sistemas",
      institution: "FIAP",
      level: "Tecnólogo",
      modality: "Presencial, online ou semipresencial, conforme a oferta",
      duration: "2 anos",
      price: educationPrice("Preço não informado"),
      evaluation: courseEvaluation(5, "ENADE", "ENADE 5/5", "https://www.fiap.com.br/graduacao/tecnologo/analise-e-desenvolvimento-de-sistemas/"),
      institutionEvaluation: institutionEvaluation("FIAP", 5, "https://www.fiap.com.br/institucional/"),
      availability: "Sem turma aberta; cadastro de interesse",
      checkedAt: CATALOG_CHECKED_AT,
      url: "https://www.fiap.com.br/graduacao/tecnologo/analise-e-desenvolvimento-de-sistemas/",
    },
    "grad-fiap-eng-software": {
      id: "grad-fiap-eng-software",
      kind: "Graduação",
      title: "Engenharia de Software",
      institution: "FIAP",
      level: "Bacharelado",
      modality: "Formato da próxima oferta a consultar",
      duration: "4 anos · 3.200 horas/aula",
      price: educationPrice("Preço não informado"),
      evaluation: courseEvaluation(5, "ENADE", "ENADE 5/5", "https://www.fiap.com.br/graduacao/bacharelado/engenharia-de-software/"),
      institutionEvaluation: institutionEvaluation("FIAP", 5, "https://www.fiap.com.br/institucional/"),
      availability: "Sem turma aberta; cadastro de interesse",
      checkedAt: CATALOG_CHECKED_AT,
      url: "https://www.fiap.com.br/graduacao/bacharelado/engenharia-de-software/",
    },
    "grad-fiap-data-science": {
      id: "grad-fiap-data-science",
      kind: "Graduação",
      title: "Banco de Dados — Data Science, Analytics, Agents & AI",
      institution: "FIAP",
      level: "Tecnólogo",
      modality: "Formato da próxima oferta a consultar",
      duration: "2 anos · 2.000 horas/aula",
      price: educationPrice("Preço não informado"),
      evaluation: courseEvaluation(5, "ENADE", "ENADE 5/5", "https://www.fiap.com.br/graduacao/tecnologo/banco-de-dados/"),
      institutionEvaluation: institutionEvaluation("FIAP", 5, "https://www.fiap.com.br/institucional/"),
      availability: "Sem turma aberta; cadastro de interesse",
      checkedAt: CATALOG_CHECKED_AT,
      url: "https://www.fiap.com.br/graduacao/tecnologo/banco-de-dados/",
    },
    "grad-fiap-cloud": {
      id: "grad-fiap-cloud",
      kind: "Graduação",
      title: "Computação em Nuvem",
      institution: "FIAP",
      level: "Tecnólogo",
      modality: "Presencial em São Paulo, conforme catálogo atual",
      duration: "2 anos",
      price: educationPrice("Preço não informado"),
      evaluation: courseEvaluation(5, "ENADE", "ENADE 5/5", "https://www.fiap.com.br/graduacao/tecnologo/computacao-em-nuvem-cloud-engineering-architecture-machine-learning/"),
      institutionEvaluation: institutionEvaluation("FIAP", 5, "https://www.fiap.com.br/institucional/"),
      availability: "Sem turma aberta; cadastro de interesse",
      checkedAt: CATALOG_CHECKED_AT,
      url: "https://www.fiap.com.br/graduacao/tecnologo/computacao-em-nuvem-cloud-engineering-architecture-machine-learning/",
    },
    "grad-pucminas-ads-ead": {
      id: "grad-pucminas-ads-ead",
      kind: "Graduação",
      title: "Tecnologia em Análise e Desenvolvimento de Sistemas",
      institution: "PUC Minas",
      level: "Tecnólogo",
      modality: "EAD · encontro síncrono semanal e provas presenciais",
      duration: "5 semestres · 2,5 anos",
      price: educationPrice("Parcelas de R$ 542,00 · tabela 2026"),
      evaluation: courseEvaluation(null, null, "Avaliação do curso não informada"),
      institutionEvaluation: institutionEvaluation("PUC Minas", 5, "https://www.pucminas.br/institucional/Paginas/a-puc-minas.aspx"),
      availability: "Oferta 2º semestre de 2026",
      checkedAt: CATALOG_CHECKED_AT,
      url: "https://vemprapuc.pucminas.br/graduacao/tecnologia-em-analise-e-desenv-de-sistemas-ead",
    },
    "grad-mackenzie-ads-ead": {
      id: "grad-mackenzie-ads-ead",
      kind: "Graduação",
      title: "Tecnologia em Análise e Desenvolvimento de Sistemas",
      institution: "Mackenzie",
      level: "Tecnólogo",
      modality: "Digital · avaliações substitutivas e finais presenciais no polo",
      duration: "5 semestres · 2,5 anos",
      price: educationPrice("R$ 650,00 por mês para ingressantes 2026/2"),
      evaluation: courseEvaluation(null, null, "Avaliação do curso não informada"),
      institutionEvaluation: institutionEvaluation("Mackenzie", 5, "https://www.mackenzie.br/universidade/assessorias-da-reitoria/comissao-propria-de-avaliacao-cpa/historico"),
      availability: "Matrículas 2026/2",
      checkedAt: CATALOG_CHECKED_AT,
      url: "https://www.mackenzie.br/graduacao/ead/tecnologia-em-analise-e-desenvolvimento-de-sistemas/atividades-academicas/pg",
    },
    "grad-mackenzie-banco-dados": {
      id: "grad-mackenzie-banco-dados",
      kind: "Graduação",
      title: "Banco de Dados: Análise, Mineração e Engenharia de Dados",
      institution: "Mackenzie",
      level: "Tecnólogo",
      modality: "Digital",
      duration: "5 semestres · 2,5 anos",
      price: educationPrice("R$ 650,00 por mês para ingressantes 2026/2"),
      evaluation: courseEvaluation(null, null, "Avaliação do curso não informada"),
      institutionEvaluation: institutionEvaluation("Mackenzie", 5, "https://www.mackenzie.br/universidade/assessorias-da-reitoria/comissao-propria-de-avaliacao-cpa/historico"),
      availability: "Matrículas 2026/2",
      checkedAt: CATALOG_CHECKED_AT,
      url: "https://computacao.mackenzie.br/tecnologia-em-banco-de-dados-analise-mineracao-e-engenharia-de-dados/",
    },
    "grad-impacta-ads": {
      id: "grad-impacta-ads",
      kind: "Graduação",
      title: "Análise e Desenvolvimento de Sistemas",
      institution: "Faculdade Impacta",
      level: "Tecnólogo",
      modality: "Presencial",
      duration: "5 semestres",
      price: educationPrice("Preço não exibido publicamente"),
      evaluation: courseEvaluation(4, "ENADE/MEC", "ENADE/MEC 4/5 · ano não indicado na página", "https://www.impacta.edu.br/premios-e-reconhecimentos"),
      institutionEvaluation: null,
      availability: "Próxima turma em agosto de 2026",
      checkedAt: CATALOG_CHECKED_AT,
      url: "https://www.impacta.edu.br/graduacoes/analise-e-desenvolvimento-de-sistemas",
    },
    "pos-fiap-frontend": {
      id: "pos-fiap-frontend",
      kind: "Pós-graduação",
      title: "Front-end Engineering",
      institution: "FIAP + Alura",
      level: "Lato sensu",
      modality: "Digital, assíncrona e hands-on · uma atividade presencial",
      duration: "10 meses · 360 horas",
      price: educationPrice("18x R$ 735,00 ou R$ 12.915,00 à vista", "Da 13ª parcela em diante há reajuste pelo IPCA."),
      evaluation: courseEvaluation(null, null, "Avaliação específica do curso não informada"),
      institutionEvaluation: institutionEvaluation("FIAP + Alura", 5, "https://www.fiap.com.br/institucional/"),
      availability: "Avise-me · sem turma aberta",
      checkedAt: CATALOG_CHECKED_AT,
      url: "https://postech.fiap.com.br/curso/front-end-engineering",
    },
    "pos-puc-eng-software": {
      id: "pos-puc-eng-software",
      kind: "Pós-graduação",
      title: "Engenharia de Software",
      institution: "PUC Minas",
      level: "Especialização",
      modality: "EAD com aulas gravadas",
      duration: "Até 18 meses · 360 horas",
      price: educationPrice("24x R$ 260,00 ou R$ 5.804,00 à vista com 7%"),
      evaluation: courseEvaluation(null, null, "Avaliação específica do curso não informada"),
      institutionEvaluation: institutionEvaluation("PUC Minas", 5, "https://www.pucminas.br/institucional/Paginas/a-puc-minas.aspx"),
      availability: "Oferta 2º semestre de 2026 confirmada",
      checkedAt: CATALOG_CHECKED_AT,
      url: "https://vemprapuc.pucminas.br/engenharia-de-software-ead-com-videoaulas",
    },
    "pos-fiap-fullstack": {
      id: "pos-fiap-fullstack",
      kind: "Pós-graduação",
      title: "Full Stack Development",
      institution: "FIAP + Alura",
      level: "Lato sensu",
      modality: "Digital, assíncrona e hands-on · uma atividade presencial",
      duration: "10 meses · 360 horas",
      price: educationPrice("18x R$ 735,00 ou R$ 12.915,00 à vista", "Da 13ª parcela em diante há reajuste pelo IPCA."),
      evaluation: courseEvaluation(null, null, "Avaliação específica do curso não informada"),
      institutionEvaluation: institutionEvaluation("FIAP + Alura", 5, "https://www.fiap.com.br/institucional/"),
      availability: "Turma de agosto",
      checkedAt: CATALOG_CHECKED_AT,
      url: "https://postech.fiap.com.br/curso/full-stack-development",
    },
    "pos-puc-data": {
      id: "pos-puc-data",
      kind: "Pós-graduação",
      title: "Ciência de Dados e Big Data",
      institution: "PUC Minas",
      level: "Especialização",
      modality: "EAD com aulas gravadas",
      duration: "Até 18 meses · 360 horas",
      price: educationPrice("24x R$ 260,00 · também 20x R$ 312,00, 15x R$ 416,00 ou 10x R$ 624,00"),
      evaluation: courseEvaluation(null, null, "Avaliação específica do curso não informada"),
      institutionEvaluation: institutionEvaluation("PUC Minas", 5, "https://www.pucminas.br/institucional/Paginas/a-puc-minas.aspx"),
      availability: "Oferta 2º semestre de 2026 confirmada",
      checkedAt: CATALOG_CHECKED_AT,
      url: "https://vemprapuc.pucminas.br/ciencia-de-dados-e-big-data-ead-com-videoaulas",
    },
    "pos-puc-qa": {
      id: "pos-puc-qa",
      kind: "Pós-graduação",
      title: "Engenharia de Qualidade e Teste de Software",
      institution: "PUC Minas",
      level: "Especialização",
      modality: "EAD com aulas gravadas",
      duration: "Até 18 meses · 360 horas",
      price: educationPrice("24x R$ 260,00 ou R$ 5.804,00 à vista com 7%"),
      evaluation: courseEvaluation(null, null, "Avaliação específica do curso não informada"),
      institutionEvaluation: institutionEvaluation("PUC Minas", 5, "https://www.pucminas.br/institucional/Paginas/a-puc-minas.aspx"),
      availability: "Oferta 2º semestre de 2026 confirmada",
      checkedAt: CATALOG_CHECKED_AT,
      url: "https://vemprapuc.pucminas.br/engenharia-de-qualidade-e-teste-de-software-ead-com-videoaulas",
    },
    "pos-puc-devops": {
      id: "pos-puc-devops",
      kind: "Pós-graduação",
      title: "DevOps & Cloud Platform Engineering com IA",
      institution: "PUC Minas",
      level: "Especialização",
      modality: "EAD com aulas gravadas",
      duration: "Até 18 meses · 360 horas",
      price: educationPrice("24x R$ 260,00 ou R$ 5.804,00 à vista com 7%"),
      evaluation: courseEvaluation(null, null, "Avaliação específica do curso não informada"),
      institutionEvaluation: institutionEvaluation("PUC Minas", 5, "https://www.pucminas.br/institucional/Paginas/a-puc-minas.aspx"),
      availability: "Oferta 2026 confirmada",
      checkedAt: CATALOG_CHECKED_AT,
      url: "https://vemprapuc.pucminas.br/devops-amp-cloud-platform-engineering-com-ia-ead-com-videoaulas",
    },
  };

  const selectCatalog = (catalog, ids) => ids.map((id) => {
    const item = catalog[id];
    if (!item) throw new Error(`Item de catálogo não encontrado: ${id}`);
    return item;
  });

  window.CAREER_CATALOGS = {
    checkedAt: CATALOG_CHECKED_AT,
    courses: COURSE_CATALOG,
    education: EDUCATION_CATALOG,
  };

  window.CAREER_GUIDES = {
    frontend: {
      duration: "16 a 24 semanas",
      weeklyHours: "6 a 8 horas por semana",
      outcome: "Criar, testar e publicar interfaces web responsivas, acessíveis e integradas a APIs.",
      courses: selectCatalog(COURSE_CATALOG, ["udemy-react-complete-guide", "udemy-web-developer-bootcamp"]),
      education: selectCatalog(EDUCATION_CATALOG, ["grad-fiap-ads", "grad-mackenzie-ads-ead", "pos-fiap-frontend", "pos-fiap-fullstack"]),
      essentials: [
        "Aprender HTML semântico e acessibilidade desde o primeiro projeto.",
        "Dominar CSS e JavaScript puro antes de depender de frameworks.",
        "Projetar para celular, teclado, leitores de tela e conexões mais lentas.",
        "Usar Git e publicar cada projeto com README e demonstração funcional.",
        "Praticar mais do que assistir: cada etapa termina com uma entrega verificável.",
      ],
      stages: [
        {
          id: "frontend-foundations",
          title: "1. Web, ferramentas e Git",
          duration: "1 a 2 semanas",
          objective: "Entender como uma página chega ao navegador e preparar um fluxo de trabalho profissional.",
          topics: ["Como a web funciona", "HTTP básico", "editor e DevTools", "terminal", "Git, commits, branches e GitHub"],
          practice: "Criar um repositório com README, uma primeira página e histórico de commits claros.",
          completion: "A página está publicada por URL e outra pessoa consegue executar o projeto seguindo o README.",
        },
        {
          id: "frontend-html",
          title: "2. HTML semântico e acessibilidade",
          duration: "2 semanas",
          objective: "Estruturar conteúdo que seja compreensível para pessoas, navegadores e tecnologias assistivas.",
          topics: ["Estrutura de documentos", "links e mídia", "formulários", "tabelas", "SEO básico", "ARIA e navegação por teclado"],
          practice: "Construir uma página de serviço com formulário completo usando HTML semântico.",
          completion: "A página possui títulos em ordem, labels, foco visível e pode ser usada apenas com teclado.",
        },
        {
          id: "frontend-css",
          title: "3. CSS moderno e responsivo",
          duration: "3 a 4 semanas",
          objective: "Transformar a estrutura em uma interface consistente para celular, tablet e desktop.",
          topics: ["Cascata e especificidade", "box model", "Flexbox", "Grid", "mobile-first", "variáveis CSS", "transições e movimento reduzido"],
          practice: "Criar um design responsivo com componentes, estados de interação e tema claro/escuro.",
          completion: "Não há rolagem horizontal e a interface funciona em diferentes larguras, zoom e preferências de movimento.",
        },
        {
          id: "frontend-javascript",
          title: "4. JavaScript no navegador",
          duration: "4 semanas",
          objective: "Adicionar comportamento e dados sem perder clareza, desempenho ou acessibilidade.",
          topics: ["Tipos e funções", "arrays e objetos", "DOM e eventos", "módulos", "async/await", "Fetch API", "localStorage"],
          practice: "Adicionar busca, filtros, validação de formulário e consumo de uma API pública.",
          completion: "A interface trata carregamento, sucesso, vazio e erro sem apresentar falhas no console.",
        },
        {
          id: "frontend-quality",
          title: "5. Qualidade, testes e performance",
          duration: "2 a 3 semanas",
          objective: "Aprender a diagnosticar e evitar problemas que afetam usuários reais.",
          topics: ["Debug com DevTools", "testes de interface", "acessibilidade", "Core Web Vitals", "otimização de imagens", "segurança no navegador"],
          practice: "Auditar um projeto e corrigir os principais problemas de acessibilidade, desempenho e usabilidade.",
          completion: "As correções e seus resultados estão documentados e os fluxos críticos foram testados.",
        },
        {
          id: "frontend-framework",
          title: "6. Componentes, framework e deploy",
          duration: "4 a 6 semanas",
          objective: "Organizar uma aplicação maior com componentes reutilizáveis e entrega automatizada.",
          topics: ["React ou Vue", "componentes", "estado", "rotas", "formulários", "design system", "build", "CI e deploy"],
          practice: "Refazer uma aplicação com componentes e configurar build e publicação automáticos.",
          completion: "A aplicação está publicada, testada e acompanhada por documentação técnica e visual.",
        },
      ],
      projects: [
        {
          level: "Inicial",
          title: "Portfólio pessoal acessível",
          description: "Página responsiva que apresenta perfil, habilidades e projetos.",
          deliverables: ["HTML semântico", "tema claro/escuro", "formulário validado", "auditoria de acessibilidade", "deploy"],
        },
        {
          level: "Intermediário",
          title: "Catálogo consumindo API",
          description: "Catálogo pesquisável com dados remotos e bons estados de interface.",
          deliverables: ["busca e filtros", "paginação", "loading e skeleton", "estado vazio e erro", "testes principais"],
        },
        {
          level: "Portfólio",
          title: "Dashboard responsivo",
          description: "Aplicação em componentes com autenticação simulada, indicadores e preferências persistidas.",
          deliverables: ["design system", "gráficos acessíveis", "persistência", "testes", "CI e deploy automático"],
        },
      ],
      materials: [
        { title: "Aprenda desenvolvimento web", provider: "MDN Web Docs", kind: "Currículo e documentação", url: "https://developer.mozilla.org/pt-BR/docs/Learn_web_development" },
        { title: "JavaScript Guide", provider: "MDN Web Docs", kind: "Documentação", url: "https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide" },
        { title: "Git e GitHub — recursos de aprendizagem", provider: "GitHub Docs", kind: "Documentação e exercícios", url: "https://docs.github.com/pt/get-started/start-your-journey/git-and-github-learning-resources" },
        { title: "Tutorial: pensar em React", provider: "React", kind: "Documentação oficial", url: "https://react.dev/learn/thinking-in-react" },
      ],
      videos: [
        { title: "Beginner's Series to JavaScript", provider: "Microsoft Learn", language: "Inglês", url: "https://learn.microsoft.com/en-us/shows/beginners-series-to-javascript/" },
        { title: "Let's Learn .NET: Web Development", provider: "Microsoft Learn", language: "Inglês", url: "https://learn.microsoft.com/en-us/shows/lets-learn-dotnet/lets-learn-dotnet-web-development" },
      ],
      certifications: [
        { title: "GitHub Foundations", provider: "GitHub", level: "Fundamentos", relevance: "Valida Git, colaboração e uso do GitHub.", url: "https://docs.github.com/en/get-started/showcase-your-expertise-with-github-certifications/about-github-certifications" },
        { title: "Microsoft Certified: Azure Fundamentals (AZ-900)", provider: "Microsoft", level: "Fundamentos", relevance: "Boa introdução a cloud e publicação de aplicações.", url: "https://learn.microsoft.com/pt-br/credentials/certifications/azure-fundamentals/" },
      ],
      branches: [
        { title: "UI Engineering", description: "Componentes, design systems, documentação e consistência visual.", nextSkills: ["Storybook", "tokens de design", "arquitetura CSS"] },
        { title: "Acessibilidade", description: "Produtos inclusivos e conformidade com padrões da web.", nextSkills: ["WCAG", "ARIA", "testes assistivos"] },
        { title: "Performance Web", description: "Carregamento, renderização e experiência percebida.", nextSkills: ["Core Web Vitals", "profiling", "otimização"] },
        { title: "Mobile híbrido", description: "Aplicações móveis usando fundamentos da web.", nextSkills: ["PWA", "React Native", "Capacitor"] },
      ],
    },

    backend: {
      duration: "20 a 28 semanas",
      weeklyHours: "7 a 10 horas por semana",
      outcome: "Construir APIs seguras, testadas, integradas a banco de dados e prontas para produção.",
      courses: selectCatalog(COURSE_CATALOG, ["udemy-nodejs-complete-guide", "udemy-python-luiz-otavio"]),
      education: selectCatalog(EDUCATION_CATALOG, ["grad-fiap-eng-software", "grad-fiap-cloud", "pos-puc-eng-software", "pos-puc-devops"]),
      essentials: [
        "Escolher uma linguagem principal — Python, JavaScript/Node ou Java — e aprofundá-la.",
        "Entender HTTP e banco relacional antes de avançar para arquiteturas complexas.",
        "Validar entrada, autenticação, autorização e erros em todas as fronteiras.",
        "Nunca armazenar senhas em texto puro nem expor segredos no repositório.",
        "Documentar e testar cada API publicada.",
      ],
      stages: [
        {
          id: "backend-language",
          title: "1. Lógica e linguagem principal",
          duration: "3 a 4 semanas",
          objective: "Construir uma base de programação suficiente para resolver problemas sem depender de frameworks.",
          topics: ["Tipos e operadores", "condicionais e loops", "funções", "coleções", "tratamento de erros", "orientação a objetos básica"],
          practice: "Criar programas de terminal para cadastro, busca e geração de relatórios.",
          completion: "O código está dividido em funções, trata entradas inválidas e possui testes básicos.",
        },
        {
          id: "backend-tooling",
          title: "2. Terminal, Git e organização",
          duration: "1 a 2 semanas",
          objective: "Trabalhar com o ambiente e a estrutura usados em projetos profissionais.",
          topics: ["Sistema de arquivos", "processos", "variáveis de ambiente", "Git flow", "dependências", "estrutura em camadas"],
          practice: "Versionar uma aplicação com branches, pull request e instruções de instalação.",
          completion: "Outra pessoa consegue configurar e executar o projeto seguindo somente o README.",
        },
        {
          id: "backend-http",
          title: "3. HTTP e APIs REST",
          duration: "3 semanas",
          objective: "Projetar contratos previsíveis entre clientes e servidores.",
          topics: ["Cliente-servidor", "métodos HTTP", "status codes", "JSON", "rotas", "middlewares", "OpenAPI"],
          practice: "Criar uma API em memória com CRUD e validação.",
          completion: "Os endpoints seguem convenções, retornam erros úteis e estão documentados.",
        },
        {
          id: "backend-database",
          title: "4. SQL e persistência",
          duration: "3 a 4 semanas",
          objective: "Modelar e consultar dados preservando integridade e desempenho.",
          topics: ["Modelagem relacional", "CRUD SQL", "JOINs", "índices", "transações", "migrations", "ORM"],
          practice: "Persistir a API em PostgreSQL e criar consultas de relatório.",
          completion: "O modelo usa chaves e restrições e as consultas importantes estão explicadas.",
        },
        {
          id: "backend-security",
          title: "5. Segurança, autenticação e testes",
          duration: "4 semanas",
          objective: "Proteger dados e comprovar o comportamento das regras de negócio.",
          topics: ["Hash de senha", "sessão ou JWT", "autorização", "OWASP", "testes unitários", "integração", "mocks"],
          practice: "Adicionar usuários, perfis de acesso e uma suíte de testes automatizados.",
          completion: "As rotas estão protegidas e os cenários críticos de sucesso e falha foram testados.",
        },
        {
          id: "backend-production",
          title: "6. Produção e observabilidade",
          duration: "4 a 6 semanas",
          objective: "Entregar e operar a API com segurança e capacidade de diagnóstico.",
          topics: ["Docker", "CI/CD", "deploy", "logs estruturados", "métricas", "cache", "filas", "backup"],
          practice: "Publicar a API com health check e monitoramento de erros.",
          completion: "Há build automático, configuração por ambiente e procedimento de recuperação documentado.",
        },
      ],
      projects: [
        { level: "Inicial", title: "Gerenciador de tarefas no terminal", description: "Aplicação local para praticar regras, persistência e testes.", deliverables: ["CRUD", "validação", "arquivo local", "testes", "README"] },
        { level: "Intermediário", title: "API de chamados", description: "Serviço REST com usuários, equipes e fluxo de atendimento.", deliverables: ["PostgreSQL", "autenticação", "papéis", "filtros", "OpenAPI", "testes"] },
        { level: "Portfólio", title: "Serviço de pedidos", description: "Back-end preparado para publicação e operação.", deliverables: ["Docker", "fila", "cache", "logs", "CI/CD", "deploy"] },
      ],
      materials: [
        { title: "Tutorial oficial de Python", provider: "Python", kind: "Documentação", url: "https://docs.python.org/pt-br/3/tutorial/" },
        { title: "Introdução ao Node.js", provider: "Node.js", kind: "Documentação e exemplos", url: "https://nodejs.org/en/learn" },
        { title: "Tutorial de PostgreSQL", provider: "PostgreSQL", kind: "Documentação prática", url: "https://www.postgresql.org/docs/current/tutorial.html" },
        { title: "OWASP Top 10", provider: "OWASP", kind: "Referência de segurança", url: "https://owasp.org/www-project-top-ten/" },
      ],
      videos: [
        { title: "Python for Beginners", provider: "Microsoft Learn", language: "Inglês", url: "https://learn.microsoft.com/en-us/shows/intro-to-python-development/python-for-beginners-1-of-44-programming-with-python" },
        { title: "Beginner's Series to JavaScript", provider: "Microsoft Learn", language: "Inglês", url: "https://learn.microsoft.com/en-us/shows/beginners-series-to-javascript/" },
      ],
      certifications: [
        { title: "GitHub Foundations", provider: "GitHub", level: "Fundamentos", relevance: "Valida versionamento, colaboração e fluxo de repositórios.", url: "https://docs.github.com/en/get-started/showcase-your-expertise-with-github-certifications/about-github-certifications" },
        { title: "AWS Certified Cloud Practitioner", provider: "AWS", level: "Fundamentos", relevance: "Introdução a cloud antes de uma certificação técnica por função.", url: "https://aws.amazon.com/certification/certified-cloud-practitioner/" },
        { title: "AWS Certified Developer — Associate", provider: "AWS", level: "Após experiência prática", relevance: "Valida desenvolvimento, teste, deploy e debug de aplicações na AWS.", url: "https://aws.amazon.com/certification/certified-developer-associate/" },
      ],
      branches: [
        { title: "APIs e microsserviços", description: "Serviços independentes, contratos e comunicação assíncrona.", nextSkills: ["mensageria", "gRPC", "sistemas distribuídos"] },
        { title: "Cloud back-end", description: "Aplicações nativas de nuvem e operação gerenciada.", nextSkills: ["serverless", "containers", "observabilidade"] },
        { title: "Segurança de aplicações", description: "Redução de riscos no código e na entrega.", nextSkills: ["OWASP", "IAM", "DevSecOps"] },
        { title: "Engenharia de dados", description: "Serviços para ingestão e processamento de dados.", nextSkills: ["ETL", "filas", "processamento distribuído"] },
      ],
    },

    fullstack: {
      duration: "28 a 40 semanas",
      weeklyHours: "8 a 12 horas por semana",
      outcome: "Entregar uma aplicação completa, da interface ao banco, com autenticação, testes e deploy.",
      courses: selectCatalog(COURSE_CATALOG, ["udemy-fullstack-angela-yu", "udemy-web-developer-bootcamp"]),
      education: selectCatalog(EDUCATION_CATALOG, ["grad-pucminas-ads-ead", "grad-mackenzie-ads-ead", "pos-fiap-fullstack", "pos-puc-eng-software"]),
      essentials: [
        "Construir uma base real de front-end e back-end antes de se chamar full stack.",
        "Aprender um fluxo completo antes de trocar constantemente de stack.",
        "Separar interface, regras de negócio e acesso a dados.",
        "Planejar segurança, erros, acessibilidade e experiência mobile desde o início.",
        "Explicar decisões técnicas e de produto no portfólio.",
      ],
      stages: [
        {
          id: "fullstack-foundations",
          title: "1. Base web, programação e Git",
          duration: "3 a 4 semanas",
          objective: "Entender o ciclo completo de uma requisição e dominar as ferramentas essenciais.",
          topics: ["HTML", "CSS", "JavaScript", "HTTP", "terminal", "Git e GitHub"],
          practice: "Criar e publicar uma landing page interativa.",
          completion: "O projeto é responsivo, versionado e publicado com documentação.",
        },
        {
          id: "fullstack-frontend",
          title: "2. Aplicação front-end",
          duration: "4 a 5 semanas",
          objective: "Construir interfaces em componentes que representem corretamente o estado da aplicação.",
          topics: ["DOM", "componentes", "estado", "rotas", "formulários", "acessibilidade", "consumo de API"],
          practice: "Criar um dashboard com dados simulados e múltiplas rotas.",
          completion: "Os fluxos de carregamento, sucesso, vazio e erro estão implementados.",
        },
        {
          id: "fullstack-backend",
          title: "3. Back-end e API",
          duration: "4 a 5 semanas",
          objective: "Implementar regras de negócio em uma API bem definida.",
          topics: ["Node.js ou Python", "REST", "validação", "middlewares", "erros", "OpenAPI"],
          practice: "Criar a API que alimenta o dashboard.",
          completion: "O CRUD está documentado e as regras estão separadas das rotas.",
        },
        {
          id: "fullstack-data-auth",
          title: "4. Banco e autenticação",
          duration: "4 semanas",
          objective: "Persistir dados e controlar com segurança quem pode fazer cada ação.",
          topics: ["PostgreSQL", "modelagem", "migrations", "ORM", "login", "sessão ou JWT", "papéis"],
          practice: "Conectar usuários, permissões e dados persistentes ao projeto.",
          completion: "A autorização é verificada no servidor e o banco possui restrições coerentes.",
        },
        {
          id: "fullstack-quality",
          title: "5. Integração e qualidade",
          duration: "3 a 4 semanas",
          objective: "Comprovar que as partes funcionam juntas e continuam funcionando após mudanças.",
          topics: ["Testes unitários", "integração", "E2E", "contrato de API", "acessibilidade", "segurança"],
          practice: "Automatizar cadastro, login e a principal operação do produto.",
          completion: "Os fluxos críticos rodam automaticamente e falhas geram evidências úteis.",
        },
        {
          id: "fullstack-delivery",
          title: "6. Entrega, operação e produto",
          duration: "4 a 6 semanas",
          objective: "Publicar a solução completa e apresentá-la como produto, não apenas como código.",
          topics: ["Docker", "CI/CD", "ambientes", "secrets", "logs", "métricas", "analytics", "feedback"],
          practice: "Publicar front-end, API e banco e conduzir uma pequena rodada de feedback.",
          completion: "O deploy é reproduzível e o case explica problema, arquitetura, resultado e próximos passos.",
        },
      ],
      projects: [
        { level: "Inicial", title: "Organizador pessoal", description: "Aplicação de produtividade focada em interface e persistência local.", deliverables: ["CRUD local", "filtros", "responsividade", "acessibilidade", "deploy"] },
        { level: "Intermediário", title: "Sistema de chamados", description: "Produto completo para abertura e acompanhamento de solicitações.", deliverables: ["front-end", "API", "PostgreSQL", "login", "papéis", "testes"] },
        { level: "Portfólio", title: "Mini SaaS colaborativo", description: "Aplicação com equipes e operação automatizada.", deliverables: ["multiusuário", "permissões", "notificações", "CI/CD", "observabilidade", "case"] },
      ],
      materials: [
        { title: "Aprenda desenvolvimento web", provider: "MDN Web Docs", kind: "Currículo e documentação", url: "https://developer.mozilla.org/pt-BR/docs/Learn_web_development" },
        { title: "Introdução ao Node.js", provider: "Node.js", kind: "Documentação e exemplos", url: "https://nodejs.org/en/learn" },
        { title: "Tutorial de PostgreSQL", provider: "PostgreSQL", kind: "Documentação prática", url: "https://www.postgresql.org/docs/current/tutorial.html" },
        { title: "Git e GitHub — recursos de aprendizagem", provider: "GitHub Docs", kind: "Documentação e exercícios", url: "https://docs.github.com/pt/get-started/start-your-journey/git-and-github-learning-resources" },
      ],
      videos: [
        { title: "Beginner's Series to JavaScript", provider: "Microsoft Learn", language: "Inglês", url: "https://learn.microsoft.com/en-us/shows/beginners-series-to-javascript/" },
        { title: "Let's Learn .NET: Web Development", provider: "Microsoft Learn", language: "Inglês", url: "https://learn.microsoft.com/en-us/shows/lets-learn-dotnet/lets-learn-dotnet-web-development" },
      ],
      certifications: [
        { title: "GitHub Foundations", provider: "GitHub", level: "Fundamentos", relevance: "Valida o fluxo de colaboração comum a toda a stack.", url: "https://docs.github.com/en/get-started/showcase-your-expertise-with-github-certifications/about-github-certifications" },
        { title: "Microsoft Certified: Azure Fundamentals (AZ-900)", provider: "Microsoft", level: "Fundamentos", relevance: "Introdução à infraestrutura onde aplicações são publicadas.", url: "https://learn.microsoft.com/pt-br/credentials/certifications/azure-fundamentals/" },
        { title: "AWS Certified Developer — Associate", provider: "AWS", level: "Após experiência prática", relevance: "Opção para aprofundar aplicações, deploy e diagnóstico na AWS.", url: "https://aws.amazon.com/certification/certified-developer-associate/" },
      ],
      branches: [
        { title: "Engenharia de produto", description: "Tecnologia orientada a resultado e experiência do usuário.", nextSkills: ["métricas", "experimentação", "UX"] },
        { title: "SaaS", description: "Produtos digitais multiusuário e recorrentes.", nextSkills: ["multi-tenant", "pagamentos", "autorização"] },
        { title: "Mobile", description: "Aplicações para dispositivos móveis conectadas às mesmas APIs.", nextSkills: ["React Native", "Flutter", "offline-first"] },
        { title: "Arquitetura", description: "Sistemas maiores e integração entre domínios.", nextSkills: ["DDD", "eventos", "sistemas distribuídos"] },
      ],
    },

    "dados-bi": {
      duration: "20 a 30 semanas",
      weeklyHours: "6 a 9 horas por semana",
      outcome: "Transformar dados brutos em modelos, análises e dashboards que apoiem decisões.",
      courses: selectCatalog(COURSE_CATALOG, ["udemy-power-bi-maven", "udemy-python-data-science"]),
      education: selectCatalog(EDUCATION_CATALOG, ["grad-fiap-data-science", "grad-mackenzie-banco-dados", "pos-puc-data", "pos-puc-eng-software"]),
      essentials: [
        "Começar pela pergunta de negócio, não pelo gráfico.",
        "Verificar qualidade, granularidade e contexto antes de analisar.",
        "Tratar SQL como habilidade central da área.",
        "Criar dashboards que orientem uma decisão concreta.",
        "Explicar método, limitações e impacto em cada projeto de portfólio.",
      ],
      stages: [
        {
          id: "data-foundations",
          title: "1. Fundamentos, negócio e planilhas",
          duration: "2 a 3 semanas",
          objective: "Traduzir necessidades de negócio em perguntas e métricas bem definidas.",
          topics: ["Tipos de dados", "métricas e KPIs", "estatística descritiva", "Excel ou Sheets", "perguntas de negócio", "ética de dados"],
          practice: "Analisar uma planilha e produzir cinco conclusões acionáveis.",
          completion: "Cada indicador possui definição, fonte, periodicidade e finalidade.",
        },
        {
          id: "data-sql",
          title: "2. SQL para análise",
          duration: "4 semanas",
          objective: "Extrair e combinar dados com consultas corretas e legíveis.",
          topics: ["SELECT", "WHERE", "JOIN", "GROUP BY", "CTEs", "subqueries", "window functions"],
          practice: "Responder perguntas de negócio usando uma base relacional.",
          completion: "As consultas foram verificadas e documentadas com a lógica dos resultados.",
        },
        {
          id: "data-preparation",
          title: "3. Limpeza, modelagem e ETL",
          duration: "3 a 4 semanas",
          objective: "Preparar dados de forma reproduzível antes da visualização.",
          topics: ["Nulos e duplicidade", "tipos", "granularidade", "modelo estrela", "Power Query", "ETL e ELT"],
          practice: "Criar um fluxo de tratamento para arquivos de múltiplas origens.",
          completion: "A base limpa possui dicionário de dados e regras de transformação registradas.",
        },
        {
          id: "data-power-bi",
          title: "4. Power BI e DAX",
          duration: "4 a 5 semanas",
          objective: "Modelar e comunicar indicadores com clareza, desempenho e segurança.",
          topics: ["Modelo semântico", "relacionamentos", "medidas DAX", "contexto de filtro", "visualização", "storytelling", "RLS"],
          practice: "Criar um dashboard executivo e uma visão operacional.",
          completion: "O relatório responde perguntas específicas e evita indicadores ambíguos ou enganosos.",
        },
        {
          id: "data-python",
          title: "5. Python e pandas",
          duration: "3 a 4 semanas",
          objective: "Automatizar preparação, exploração e validação de dados.",
          topics: ["Python básico", "pandas", "notebooks", "limpeza", "agregação", "visualização", "automação"],
          practice: "Reproduzir em Python parte da preparação e análise anterior.",
          completion: "O notebook executa do início ao fim e apresenta conclusões sustentadas pelos dados.",
        },
        {
          id: "data-platform",
          title: "6. Governança, cloud e portfólio",
          duration: "4 a 6 semanas",
          objective: "Entregar uma solução analítica sustentável e pronta para compartilhamento.",
          topics: ["Workspaces", "refresh", "segurança", "linhagem", "Microsoft Fabric", "Lakehouse e Warehouse", "Git", "documentação"],
          practice: "Publicar uma solução com pipeline, modelo semântico e relatório.",
          completion: "O case apresenta fonte, transformação, modelo, segurança, dashboard e impacto esperado.",
        },
      ],
      projects: [
        { level: "Inicial", title: "Análise de vendas", description: "Estudo exploratório com perguntas e indicadores definidos.", deliverables: ["limpeza", "SQL", "KPIs", "gráficos", "conclusões"] },
        { level: "Intermediário", title: "Dashboard de atendimento", description: "Painel operacional e gerencial sobre chamados.", deliverables: ["Power Query", "modelo estrela", "DAX", "drill-through", "RLS"] },
        { level: "Portfólio", title: "Solução analítica ponta a ponta", description: "Pipeline, modelo e consumo de dados em uma solução governada.", deliverables: ["pipeline", "SQL ou Python", "modelo semântico", "governança", "dashboard", "case"] },
      ],
      materials: [
        { title: "Tutorial de PostgreSQL", provider: "PostgreSQL", kind: "Documentação prática", url: "https://www.postgresql.org/docs/current/tutorial.html" },
        { title: "Tutorial oficial de Python", provider: "Python", kind: "Documentação", url: "https://docs.python.org/pt-br/3/tutorial/" },
        { title: "Getting started tutorials", provider: "pandas", kind: "Documentação prática", url: "https://pandas.pydata.org/docs/getting_started/intro_tutorials/" },
        { title: "Trilha de carreira para analista de dados", provider: "Microsoft Learn", kind: "Cursos autoguiados", url: "https://learn.microsoft.com/en-us/training/career-paths/data-analyst/" },
      ],
      videos: [
        { title: "Design and manage analytics solutions using Power BI (PL-300)", provider: "Microsoft Learn", language: "Inglês", url: "https://learn.microsoft.com/en-gb/shows/on-demand-instructor-led-training-series/pl-300-08-fy25" },
        { title: "Python for Beginners", provider: "Microsoft Learn", language: "Inglês", url: "https://learn.microsoft.com/en-us/shows/intro-to-python-development/python-for-beginners-1-of-44-programming-with-python" },
      ],
      certifications: [
        { title: "Microsoft Certified: Azure Data Fundamentals (DP-900)", provider: "Microsoft", level: "Fundamentos", relevance: "Valida conceitos relacionais, não relacionais e de analytics.", url: "https://learn.microsoft.com/pt-br/credentials/certifications/azure-data-fundamentals/" },
        { title: "Microsoft Certified: Power BI Data Analyst Associate (PL-300)", provider: "Microsoft", level: "Intermediário", relevance: "Diretamente alinhada a preparação, modelagem, análise e segurança no Power BI.", url: "https://learn.microsoft.com/pt-br/credentials/certifications/power-bi-data-analyst-associate/" },
        { title: "Microsoft Certified: Fabric Analytics Engineer Associate (DP-600)", provider: "Microsoft", level: "Intermediário a avançado", relevance: "Indicada após domínio de SQL, DAX, modelos semânticos e ativos do Fabric.", url: "https://learn.microsoft.com/pt-br/credentials/certifications/fabric-analytics-engineer-associate/" },
      ],
      branches: [
        { title: "Business Intelligence", description: "Modelagem, visualização e tomada de decisão.", nextSkills: ["Power BI", "DAX", "storytelling"] },
        { title: "Analytics Engineering", description: "Camada analítica confiável entre engenharia e BI.", nextSkills: ["SQL avançado", "dbt", "testes de dados"] },
        { title: "Engenharia de Dados", description: "Ingestão, transformação e plataformas de dados.", nextSkills: ["pipelines", "Spark", "lakehouse"] },
        { title: "Ciência de Dados", description: "Modelagem estatística e previsão.", nextSkills: ["estatística", "machine learning", "experimentos"] },
      ],
    },

    qa: {
      duration: "16 a 24 semanas",
      weeklyHours: "6 a 8 horas por semana",
      outcome: "Planejar testes, encontrar riscos, registrar defeitos e automatizar fluxos críticos.",
      courses: selectCatalog(COURSE_CATALOG, ["udemy-software-testing-masterclass", "udemy-introduction-software-qa"]),
      education: selectCatalog(EDUCATION_CATALOG, ["grad-fiap-ads", "grad-impacta-ads", "pos-puc-qa", "pos-puc-eng-software"]),
      essentials: [
        "QA existe para reduzir risco, não apenas para executar passos.",
        "Todo teste precisa de objetivo e resultado esperado.",
        "Um bom relato de defeito deve ser reproduzível por outra pessoa.",
        "Automação complementa a análise humana e deve focar regressões valiosas.",
        "Os fluxos de maior impacto vêm antes da busca por cobertura total.",
      ],
      stages: [
        {
          id: "qa-foundations",
          title: "1. Fundamentos de qualidade",
          duration: "2 semanas",
          objective: "Entender onde testes entram no desenvolvimento e como priorizar esforço por risco.",
          topics: ["Ciclo de desenvolvimento", "níveis e tipos de teste", "princípios de teste", "risco", "qualidade em Agile e DevOps"],
          practice: "Mapear riscos de uma tela de cadastro e priorizar o que testar.",
          completion: "Os riscos estão classificados por impacto e probabilidade e ligados a cenários de teste.",
        },
        {
          id: "qa-design",
          title: "2. Técnicas e casos de teste",
          duration: "3 semanas",
          objective: "Criar um conjunto enxuto de testes que encontre falhas relevantes.",
          topics: ["Partição de equivalência", "valor limite", "tabela de decisão", "transição de estado", "teste exploratório"],
          practice: "Criar casos positivos, negativos e de borda para um formulário.",
          completion: "Os casos são rastreáveis aos requisitos e cobrem regras e riscos principais.",
        },
        {
          id: "qa-defects",
          title: "3. Bugs, evidências e colaboração",
          duration: "2 semanas",
          objective: "Comunicar problemas de forma objetiva e útil para o time.",
          topics: ["Bug report", "severidade", "prioridade", "evidências", "GitHub Issues", "refinamento e critérios de aceite"],
          practice: "Testar uma aplicação de demonstração e registrar os defeitos encontrados.",
          completion: "Outra pessoa consegue reproduzir cada defeito usando as informações registradas.",
        },
        {
          id: "qa-api-sql",
          title: "4. API, HTTP e SQL",
          duration: "3 semanas",
          objective: "Validar serviços e dados sem depender apenas da interface gráfica.",
          topics: ["REST", "métodos e status HTTP", "JSON", "Postman ou Bruno", "contrato", "SQL básico", "validação de dados"],
          practice: "Testar o CRUD de uma API e conferir persistência no banco.",
          completion: "A coleção cobre sucesso, validação, autorização e dados inválidos.",
        },
        {
          id: "qa-automation",
          title: "5. Automação web com Playwright",
          duration: "4 a 5 semanas",
          objective: "Automatizar os fluxos de maior valor com testes confiáveis e legíveis.",
          topics: ["JavaScript ou TypeScript", "Playwright", "locators", "assertions", "fixtures", "page objects", "massa de teste"],
          practice: "Automatizar cadastro, login e uma jornada principal.",
          completion: "Os testes são independentes, evitam esperas frágeis e geram relatório de execução.",
        },
        {
          id: "qa-pipeline",
          title: "6. CI, performance e acessibilidade",
          duration: "3 a 4 semanas",
          objective: "Integrar qualidade ao fluxo de entrega e ampliar a visão além do teste funcional.",
          topics: ["GitHub Actions", "testes em CI", "pirâmide de testes", "performance básica", "acessibilidade", "métricas de qualidade"],
          practice: "Executar os testes automaticamente em pull requests e guardar evidências.",
          completion: "O pipeline bloqueia regressão crítica e permite diagnosticar rapidamente uma falha.",
        },
      ],
      projects: [
        { level: "Inicial", title: "Plano de teste de cadastro", description: "Análise funcional completa de um fluxo simples.", deliverables: ["riscos", "cenários", "casos", "bugs", "evidências"] },
        { level: "Intermediário", title: "Suíte de testes de API", description: "Validação automatizada de um serviço REST.", deliverables: ["CRUD", "validação", "autorização", "dados variáveis", "relatório"] },
        { level: "Portfólio", title: "Automação E2E em CI", description: "Regressão de interface executada em pipeline.", deliverables: ["Playwright", "fixtures", "relatório HTML", "traces", "GitHub Actions"] },
      ],
      materials: [
        { title: "Certified Tester Foundation Level 4.0", provider: "ISTQB", kind: "Syllabus e provas de exemplo", url: "https://www.istqb.org/certifications/certified-tester-foundation-level-ctfl-v4-0/" },
        { title: "Playwright Test", provider: "Playwright", kind: "Documentação e exemplos", url: "https://playwright.dev/docs/intro" },
        { title: "GitHub Actions — primeiros passos", provider: "GitHub Docs", kind: "Documentação", url: "https://docs.github.com/pt/actions/get-started" },
        { title: "Web Content Accessibility Guidelines", provider: "W3C WAI", kind: "Padrão de acessibilidade", url: "https://www.w3.org/WAI/standards-guidelines/wcag/" },
      ],
      videos: [
        { title: "Getting started with end-to-end testing with Playwright", provider: "Microsoft Learn", language: "Inglês", url: "https://learn.microsoft.com/en-us/shows/getting-started-with-end-to-end-testing-with-playwright/" },
        { title: "End to End Testing with Playwright", provider: "Microsoft Learn", language: "Inglês", url: "https://learn.microsoft.com/en-us/shows/learn-tv-static-web-apps-code-to-scale/end-to-end-testing-with-playwright" },
      ],
      certifications: [
        { title: "ISTQB Certified Tester Foundation Level 4.0", provider: "ISTQB", level: "Fundamentos", relevance: "Base reconhecida de terminologia, técnicas, processo e gestão de testes.", url: "https://www.istqb.org/certifications/certified-tester-foundation-level-ctfl-v4-0/" },
        { title: "GitHub Foundations", provider: "GitHub", level: "Fundamentos", relevance: "Útil para colaboração, registro de defeitos e versionamento de testes.", url: "https://docs.github.com/en/get-started/showcase-your-expertise-with-github-certifications/about-github-certifications" },
        { title: "GitHub Actions", provider: "GitHub", level: "Intermediário", relevance: "Relevante para integrar testes automatizados a CI/CD.", url: "https://docs.github.com/en/get-started/showcase-your-expertise-with-github-certifications/about-github-certifications" },
      ],
      branches: [
        { title: "QA funcional", description: "Validação de regras e experiência do negócio.", nextSkills: ["requisitos", "exploratório", "testes de aceitação"] },
        { title: "Automação e SDET", description: "Frameworks de teste construídos com engenharia de software.", nextSkills: ["programação", "arquitetura de testes", "CI"] },
        { title: "Performance", description: "Comportamento sob carga e identificação de gargalos.", nextSkills: ["carga", "latência", "observabilidade"] },
        { title: "Segurança", description: "Testes orientados a vulnerabilidades e abuso.", nextSkills: ["OWASP", "testes de API", "DevSecOps"] },
      ],
    },

    devops: {
      duration: "24 a 36 semanas",
      weeklyHours: "7 a 10 horas por semana",
      outcome: "Automatizar build, teste, infraestrutura, deploy e monitoramento de aplicações.",
      courses: selectCatalog(COURSE_CATALOG, ["udemy-decoding-devops", "udemy-docker-kubernetes-practical"]),
      education: selectCatalog(EDUCATION_CATALOG, ["grad-fiap-cloud", "grad-fiap-eng-software", "pos-puc-devops", "pos-puc-eng-software"]),
      essentials: [
        "Aprender Linux, redes e Git antes de Kubernetes.",
        "Criar automações reproduzíveis, revisáveis e seguras.",
        "Nunca armazenar segredos no repositório ou na imagem da aplicação.",
        "Considerar o deploy completo apenas quando há observabilidade e rollback.",
        "Tratar DevOps como cultura e fluxo de entrega, não como coleção de ferramentas.",
      ],
      stages: [
        {
          id: "devops-linux-network",
          title: "1. Linux e redes",
          duration: "3 a 4 semanas",
          objective: "Entender o ambiente onde serviços executam e como uma requisição chega até eles.",
          topics: ["Terminal", "arquivos e permissões", "processos e serviços", "TCP/IP", "DNS", "HTTP", "SSH"],
          practice: "Configurar um serviço local e diagnosticar falhas de processo, porta e resolução de nome.",
          completion: "O aluno explica o caminho da requisição e usa comandos para localizar falhas básicas.",
        },
        {
          id: "devops-git-scripting",
          title: "2. Git e automação",
          duration: "3 semanas",
          objective: "Automatizar tarefas repetitivas em um fluxo colaborativo e auditável.",
          topics: ["Branches e pull requests", "Bash", "Python básico", "YAML", "variáveis de ambiente", "idempotência"],
          practice: "Criar scripts de build, validação, health check e backup.",
          completion: "Os scripts têm códigos de saída, documentação e podem ser executados novamente com segurança.",
        },
        {
          id: "devops-containers",
          title: "3. Containers",
          duration: "3 a 4 semanas",
          objective: "Empacotar aplicações em ambientes consistentes e mínimos.",
          topics: ["Imagens", "Dockerfile", "volumes", "redes", "Docker Compose", "registry", "segurança de imagem"],
          practice: "Containerizar uma aplicação com banco e persistência.",
          completion: "O ambiente completo sobe com um comando e possui health checks.",
        },
        {
          id: "devops-cicd",
          title: "4. Integração e entrega contínuas",
          duration: "3 a 4 semanas",
          objective: "Transformar cada mudança em uma entrega testada, rastreável e segura.",
          topics: ["GitHub Actions", "jobs e dependências", "artefatos", "cache", "secrets", "ambientes", "aprovação e rollback"],
          practice: "Automatizar testes, build e publicação em ambientes separados.",
          completion: "Pull requests validam o código e a branch principal publica sem usar segredos no repositório.",
        },
        {
          id: "devops-cloud-iac",
          title: "5. Cloud e infraestrutura como código",
          duration: "4 a 5 semanas",
          objective: "Provisionar recursos de forma repetível, revisável e consciente de custos.",
          topics: ["Compute", "storage", "rede", "IAM", "custos", "Terraform", "state", "modules"],
          practice: "Provisionar um ambiente pequeno com Terraform.",
          completion: "O plan é revisável, o state está protegido e a infraestrutura pode ser recriada.",
        },
        {
          id: "devops-operations",
          title: "6. Orquestração, observabilidade e SRE",
          duration: "5 a 7 semanas",
          objective: "Operar serviços com visibilidade, confiabilidade e resposta organizada a incidentes.",
          topics: ["Kubernetes básico", "deployments e services", "config e secrets", "logs", "métricas e alertas", "SLI/SLO", "runbooks", "post-mortem"],
          practice: "Publicar um serviço, criar alerta, simular uma falha e executar rollback.",
          completion: "A aplicação é observável e possui runbook, post-mortem e ação preventiva documentados.",
        },
      ],
      projects: [
        { level: "Inicial", title: "Kit de automação local", description: "Scripts reutilizáveis para tarefas operacionais.", deliverables: ["Bash ou Python", "health check", "logs", "backup", "README"] },
        { level: "Intermediário", title: "Aplicação com Docker Compose", description: "Ambiente completo e reproduzível para desenvolvimento.", deliverables: ["aplicação", "banco", "volumes", "health checks", "rede"] },
        { level: "Portfólio", title: "Plataforma de entrega", description: "Infraestrutura e pipeline com operação documentada.", deliverables: ["CI/CD", "Terraform", "cloud", "monitoramento", "rollback", "runbook"] },
      ],
      materials: [
        { title: "Get started with Docker", provider: "Docker", kind: "Documentação e workshop", url: "https://docs.docker.com/get-started/" },
        { title: "GitHub Actions — primeiros passos", provider: "GitHub Docs", kind: "Documentação", url: "https://docs.github.com/pt/actions/get-started" },
        { title: "Learning environment", provider: "Kubernetes", kind: "Documentação e laboratório", url: "https://kubernetes.io/docs/setup/learning-environment/" },
        { title: "Terraform Associate 004 — trilha oficial", provider: "HashiCorp", kind: "Tutoriais e laboratórios", url: "https://developer.hashicorp.com/terraform/tutorials/certification-004/associate-study-004" },
        { title: "Linux Foundation learning paths", provider: "Linux Foundation", kind: "Trilhas de aprendizagem", url: "https://training.linuxfoundation.org/learning-paths/" },
      ],
      videos: [
        { title: "DevOps Fundamentals", provider: "Microsoft Learn", language: "Inglês", url: "https://learn.microsoft.com/en-us/shows/devops-fundamentals/" },
        { title: "The DevOps Lab", provider: "Microsoft Learn", language: "Inglês", url: "https://learn.microsoft.com/en-us/shows/devops-lab/" },
      ],
      certifications: [
        { title: "Linux Foundation Certified IT Associate (LFCA)", provider: "Linux Foundation", level: "Fundamentos", relevance: "Base de Linux, sistemas, redes, cloud, segurança e DevOps.", url: "https://training.linuxfoundation.org/certification/certified-it-associate/" },
        { title: "GitHub Actions", provider: "GitHub", level: "Intermediário", relevance: "Valida automação de workflows e pipelines no GitHub.", url: "https://docs.github.com/en/get-started/showcase-your-expertise-with-github-certifications/about-github-certifications" },
        { title: "HashiCorp Certified: Terraform Associate 004", provider: "HashiCorp", level: "Após laboratórios práticos", relevance: "Valida fundamentos e fluxo de infraestrutura como código.", url: "https://developer.hashicorp.com/certifications/infrastructure-automation" },
        { title: "Kubernetes and Cloud Native Associate (KCNA)", provider: "CNCF e Linux Foundation", level: "Fundamentos cloud native", relevance: "Indicada após containers e fundamentos de Kubernetes.", url: "https://www.cncf.io/training/certification/" },
      ],
      branches: [
        { title: "Cloud Engineering", description: "Infraestrutura, identidade, redes e custos em cloud.", nextSkills: ["AWS, Azure ou GCP", "IAM", "FinOps"] },
        { title: "Site Reliability Engineering", description: "Confiabilidade mensurável e resposta a incidentes.", nextSkills: ["SLI/SLO", "incident response", "engenharia de confiabilidade"] },
        { title: "Platform Engineering", description: "Plataformas internas e experiência de desenvolvimento.", nextSkills: ["self-service", "Kubernetes", "developer experience"] },
        { title: "DevSecOps", description: "Segurança incorporada a código, infraestrutura e entrega.", nextSkills: ["SAST e DAST", "supply chain", "policy as code"] },
      ],
    },
  };
})();
